### ISSUE TITLE
Problem with nanmax() function in Matlab

### ISSUE THREAD

**Issue by PTRRupprecht** [yu-lab-vt/AQuA#14]
First, thanks a lot for this interesting and well-documented toolbox!

I was just trying out the Matlab version and noticed a minor problem: When hitting the "Extract" button, an error occurs in the function `getPropagationCentroidQuad()`. The culprit was the `nanmax()` function.

By replacing e.g.

`[~,id] = nanmax(pixNumChangeRateMultiThrAbs,[],2);`

simply with

`[~,id] = nanmax(pixNumChangeRateMultiThrAbs,2);`,

(and similar replacements of other occurrences of the `nanmax` function) the problem could be solved. This was the case for the MATLAB R2020b version, and it might be a bug of this Matlab version, because the original code is fine according to the official Matlab documentation. I just wanted to mention this issue here so that others who run in this very same problem will know what to do.

Best,
Peter

**Comment by XuelongMi** [comment]
Hi Peter,

Thank you for your reminder. But today I tested the AQuA code on MATLAB R2020b and MATLAB R2022b, and I couldn't find the same error. The command `[~,id] = nanmax(pixNumChangeRateMultiThrAbs,[],2);` still works. Could you give me an example, like the content of `pixNumChangeRateMultiThrAbs`?

And I also tried to generate random 2D matrix through `data = randn(100,100)` and then apply `[~,id] = nanmax(data,[],2)`, and it works. So I think the function doesn't change due to the MATLAB update.

Best Wishes,
Xuelong
