### ISSUE TITLE
Index error occurring with big file sizes (>4GB)

### ISSUE THREAD

**Issue by janreising** [yu-lab-vt/AQuA#6]
Hi,

thanks a lot for providing this tools. It has been fantastic to work with so far, but I am running into problems when trying to process bigger file sizes. The file I am working with is ca. 7GB big and includes 2500 frames at 1200x12000 pixels. Seconds to minutes into the "reading" step of the 'aqua_cmd.m', I am getting the following errors: 

```
Index exceeds the number of array elements (2).

Error in ui.over.getOv (line 18)
T = sz(3);

Error in fea.gatherRes (line 30)
ov0 = ui.over.getOv([],evt,size(dRecon),dRecon);

Error in aqua_cmd (line 201)
res = fea.gatherRes(datOrg,opts,evtLstE,ftsLstE,dffMatE,dMatE,riseLstE,datRE);

```
Initially, I thought it the crash occurred due to a high number of frames but playing around with cropping & fewer frames, points towards an upper file size limit which is somewhere between 4 and 4.2GB. For example, 1500 frames at 1200x1200 (4.22GB) crashes, while 1500 frames at 1176x1180 (4.07GB) works. So does 1300 frames at 1200x1200 (3.66GB). 

The issue is not related to insufficient RAM, since the code seems to crash before the file is actually being loaded. Just out of curiosity, I also tried to process the files with the GUI, in which case the GUI seems to load the file but can only access the very first frame. 

I am not very familiar with Matlab, so I apologize in advance if this is an obvious mistake on my part. Hope there is an easy fix for this, since I would love to use the tool and am bit hesitant to split my files into smaller stacks that can be processed separately.

Thanks again!

**Comment by yu-lab-vt** [comment]
Can you tell us how large your RAM is?

**Comment by janreising** [comment]
I have tried with 32GB and 128GB, which produces the same error.

**Comment by XuelongMi** [comment]
Hi, could you tell me your data format? I've tried to reproduce your problem by generating some noise video 1200X1200X2000, then I found there is a limitation for '.tif' file. I cannot even output such video into .tiff format. The maximum size limitation for '.tiff' file or '.tif' file is 4GB, and we use a built-in function in Matlab to read data, so I think that's the problem. Now I cannot generate such large data in '.tif' format to debug. Thus, I'm curious about your data format. Or, can you generate pure noise data then share it with me so that I can adjust the code to fix the problem?

**Comment by janreising** [comment]
Classic tiff is limited to 4GB file size, in that case you can just use BIGTiff file format, which I am doing. I personally use python and here is some code to generate bigger files:

```
import numpy as np
import tifffile as tif

# create random matrix
dim = (600, 1200, 1200)
rand_matrix = np.random.rand(*dim)

# save file
tif.imsave("dummy.tiff", data=rand_matrix)
```
Also, I google a bit and found this code doing something similar as the tiffile package in python: [https://www.mathworks.com/matlabcentral/fileexchange/35684-multipage-tiff-stack]

Here some dummy code in matlab: 

```
%reset environment
clearvars;
clear options;

% create rand matrix
rand_matrix = rand(400, 1200, 1200);

% set options
options.overwrite = true;
options.big = true;

% save file
saveastiff(rand_matrix, 'dummy.tiff', options);

% load file
% x = loadtiff('dummy.tiff');
```

Thanks for getting back to me so quickly!

**Comment by XuelongMi** [comment]
Thank you for your information, I generally know what happens, but still need your help to locate the problem. 

By using your code to generate BIGTIFF file, I generate a 6.43GB tiff and test it with AQuA, the reading step can work. I cannot reproduce the same error by generating BIGTIFF file. So I think it's not the size problem. Will you meet the same reading problem with the data generated by your python code?

There are many settings to save a BIGTIFF file, but the code for generating bigger files only uses one default setting, which I think is different from your data. And combine your description of the error, **I find the reading step only reads one frame of your data**, so that the error report is in that form. I'm not sure why the reading step works for the cropped data smaller than 4GB, maybe the crop operation will change the data format according to size (like from BIGTIFF to TIFF). To solve the problem, I need the details about your data. Could you send me one example data **with the same error** (No matter how large. It will be better to send me a very small crop with the same data format)? Or if it's inconvenient, another possible way to use the tool is to do spatial downsampling first, then the size will be smaller and the tool can work.

**Comment by janreising** [comment]
Hi, 
sorry for the long delay in replying. Here is a link for the smallest file that still produces the error: 
https://drive.google.com/file/d/11iZJOYksGGKVAO1U1idzB2bxJXPjio0B/view?usp=sharing

Surprisingly, I also don't get the error with the dummy files. Downsampling is unfortunately not really an option. The final TIFFs will be in the dozens of Gigabytes, so I'll just run into the same error eventually. Is there another way to load the data? Maybe load it as .h5 or read the images sequentially from folder instead of a tiff stack?

**Comment by XuelongMi** [comment]
Hi,
After downloading your data, I adjusted the code of the reading procedure. Now for the downloaded data, it can read it successfully. You can download the newest code in GitHub to test your other datasets.

**Comment by janreising** [comment]
Thank you so much! I have been testing it for the last couple of hours and everything seems to be working now. Unfortunately, I am maxing out the available RAM for the biggest files, so I couldn't test it with those yet. However, I don't expect it to matter if the mid-sized files work!
